name: yt_splitter
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  path: ^1.7.0
  xdg_directories: ^0.1.2

dev_dependencies:
  pedantic: ^1.9.0
